name: CI

on:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: false
    - name: Go Lint
      uses: golangci/golangci-lint-action@v3
      with:
        skip-pkg-cache: true
        skip-build-cache: true
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      uses: docker/build-push-action@v5
      with:
        push: false
        file: Dockerfile
        context: ./
