name: Release

on:
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare image metadata
      uses: docker/metadata-action@v4
      id: meta
      with:
        images: xdesigns/longhorn-cli
        tags: |
          type=ref,event=tag

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        push: true
        file: Dockerfile
        context: ./
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}

  goreleaser:
    needs: [build-push]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
        # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
